SELECT A.ID_GENERAL, A.FECHA_RECEPCION, TD.NOMBRE, FC.NOMBRE, C.VALOR_1, C.VALOR_2
  FROM MUESTRAS A, DETERMINACIONES B, DATOS_DETERMINACIONES C, FORMULAS F, TIPOS_DETERMINACION TD, FORMULAS_CAMPOS FC
 WHERE A.ID_MUESTRA = B.MUESTRA_ID
   AND B.FORMULA_ID = F.ID_FORMULA
   AND B.ID_DETERMINACION = C.DETERMINACION_ID
	AND C.CAMPO_ID = FC.ID_CAMPO
--	AND C.CAMPO_ID = F.CAMPO_ID_RESULTADO   
	AND B.TIPO_DETERMINACION_ID = TD.ID_TIPO_DETERMINACION
   AND A.FECHA_RECEPCION >= '2013-01-01' AND A.FECHA_RECEPCION <= '2013-12-31'
   AND B.TIPO_DETERMINACION_ID IN (1640)
ORDER BY 1,2,C.CAMPO_ID