

SELECT TM.ID_TIPO_MUESTRA,TM.NOMBRE, M.IPA, count(*)
FROM MUESTRAS M, CLIENTES C, TIPOS_MUESTRA TM, TIPOS_ANALISIS TA, DECODIFICADORA D
WHERE M.ANNO = 2013 AND M.ANULADA = 0 AND M.FECHA_RECEPCION >= '2013-01-01' AND M.FECHA_RECEPCION <= '2013-12-31'
  AND M.FECHA_PREV_FIN >= M.FECHA_CIERRE 
  AND M.CERRADA <> 0
  AND M.CLIENTE_ID = C.ID_CLIENTE
  AND M.TIPO_MUESTRA_ID = TM.ID_TIPO_MUESTRA
  AND M.TIPO_ANALISIS_ID = TA.ID_TIPO_ANALISIS
  AND M.MOTIVO_RETRASO_ID = D.VALOR AND D.CODIGO = 155
  AND TM.SECTOR_ID = 7
GROUP BY TM.ID_TIPO_MUESTRA,TM.NOMBRE, M.IPA
UNION 
SELECT TM.ID_TIPO_MUESTRA,TM.NOMBRE, M.IPA, count(*)
FROM MUESTRAS M, CLIENTES C, TIPOS_MUESTRA TM, TIPOS_ANALISIS TA, DECODIFICADORA D
WHERE M.ANNO = 2013 AND M.ANULADA = 0 AND M.FECHA_RECEPCION >= '2013-01-01' AND M.FECHA_RECEPCION <= '2013-12-31'
  AND (M.FECHA_PREV_FIN < M.FECHA_CIERRE OR M.CERRADA = 0)
  AND M.FECHA_RECEPCION < M.FECHA_PREV_FIN
  AND M.CLIENTE_ID = C.ID_CLIENTE
  AND M.TIPO_MUESTRA_ID = TM.ID_TIPO_MUESTRA
  AND M.TIPO_ANALISIS_ID = TA.ID_TIPO_ANALISIS
  AND M.MOTIVO_RETRASO_ID = D.VALOR AND D.CODIGO = 155
  AND TM.SECTOR_ID = 7
GROUP BY TM.ID_TIPO_MUESTRA,TM.NOMBRE, M.IPA
