SELECT D.PRODUCTO,C.DESCRIPCION, A.PRECIO, SUM(A.NUMERO_BOTES)
  FROM ALODINE_PLANIFICACION A, ALODINE_LOTES B, ALODINE_CAPACIDAD C, ALODINE D
 WHERE A.LOTE_ID = B.ID_LOTE
   AND B.FECHA_ALTA BETWEEN '2013-10-01' AND '2013-10-31'
   AND A.CAPACIDAD_ID = C.ID_CAPACIDAD
   AND B.ALODINE_ID = D.ID_ALODINE
GROUP BY D.PRODUCTO,C.DESCRIPCION, A.PRECIO