Attribute VB_Name = "Constantes_Equipos"
Public Enum EQ_TIPOS_EQUIPOS
    TIPO_EQUIPO_TORCOMETRO = 8
End Enum

Public Enum CAL_ESTADOS
    CAL_ESTADO_PREVISTA = 0
    CAL_ESTADO_REALIZADA = 1
    CAL_ESTADO_REVISADA = 2
    CAL_ESTADO_ANULADA = 3
End Enum

Public Enum CAL_RESULTADOS
    CAL_RESULTADO_CONFORME = 0
    CAL_RESULTADO_NO_CONFORME = 1
    CAL_RESULTADO_REQ_AJUSTE = 2
End Enum

Public Enum VER_ESTADOS
    VER_ESTADO_PREVISTA = 0
    VER_ESTADO_REALIZADA = 1
    VER_ESTADO_REVISADA = 2
    VER_ESTADO_ANULADA = 3
End Enum

Public Enum VER_RESULTADOS
    VER_RESULTADO_CONFORME = 0
    VER_RESULTADO_NO_CONFORME = 1
    VER_RESULTADO_REQ_AJUSTE = 2
End Enum

Public Enum EQUIPOS_EVENTOS
    EVT_RECEPCION_EQUIPO = 1
    EVT_CALIBRACION_REALIZADA = 2
    EVT_VERIFICACION_REALIZADA = 3
    EVT_MANTENIMIENTO_REALIZADO = 4
    EVT_PUESTA_EN_SERVICIO = 5
    EVT_PUESTA_EN_FUERA_DE_SERVICIO = 6
    EVT_ENVIO_DE_EQUIPO = 7
    EVT_CAMBIO_EDICION_DE_EQUIPO = 8
    EVT_REG_PREVISTO_ELIMINADO = 9
    EVT_CAMBIO_ESTADO_EQUIPO = 10
    EVT_REPARACION_EQUIPO = 11
'M1326-I
    EVT_APERTURA_CIERRE_EQUIPO = 12
'M1326-F
End Enum

Public Enum EQUIPOS_EVENTOS_MOTIVOS
    EVTRZ_OTROS = 0
    EVTRZ_INICIAL = 1
    EVTRZ_TRAS_TRASLADO = 2
    EVTRZ_RESULTADO_OK = 3
    EVTRZ_RESULTADO_NEG = 4
    EVTRZ_TRAS_AVERIA_REPARACION = 5
    EVTRZ_CALIBRACION_NO_CONFORME = 6
    EVTRZ_VERIFICACION_NO_CONFORME = 7
    EVTRZ_MANTENIMIENTO_NO_CONFORME = 8
    EVTRZ_TRASLADO = 9
    EVTRZ_AVERIA = 10
    EVTRZ_REPARACION_AVERIA = 11
    EVTRZ_CALIBRACION_EXTERNA = 12
    EVTRZ_VERIFICACION_EXTERNA = 13
    EVTRZ_MANTENIMIENTO_EXTERNO = 14
    EVTRZ_POR_SUST_ACCESORIO = 15
    EVTRZ_RESULTADO_NEG_1A_VEZ = 16
    EVTRZ_ALTA_DE_EQUIPO = 17
    EVTRZ_BAJA_DE_EQUIPO = 18
    EVTRZ_BAJA_DE_EQUIPO_TRASLADO = 19
    EVTRZ_BAJA_DE_EQUIPO_AVERIA = 20
    EVTRZ_CALIBRACION_ELIMINADA = 21
    EVTRZ_VERIFICACION_ELIMINADA = 22
    EVTRZ_MANTENIMIENTO_ELIMINADO = 23
    EVTR_APERTURA = 24
    EVTR_CIERRE = 25
End Enum
Public Enum EQUIPOS_CVM_TIPOS
    CVM_TIPO_CALIBRACION = 0
    CVM_TIPO_VERIFICACION = 1
    CVM_TIPO_MANTENIMIENTO = 2
End Enum

Public Enum EQUIPOS_CVM_ESTADO
    CVM_ESTADO_PREVISTO = 0
    CVM_ESTADO_CONFORME = 1
    CVM_ESTADO_NO_CONFORME = 2
End Enum

Public Enum EQUIPOS_TIPOS_PARAMETROS_RESULTADOS
    PARAM_CUALIDAD = 0
    PARAM_PATRON_EQUIPO = 1
    PARAM_PATRON_REACTIVO = 2
End Enum

Public Enum ENUM_EQUIPOS_PERIODICIDAD
    ENUM_EQUIPOS_PERIODICIDAD_ANTES_ENSAYO = 13
    ENUM_EQUIPOS_PERIODICIDAD_ANTES_CADA_ENSAYO = 12
End Enum


