Attribute VB_Name = "Constantes"
Public Declare Function ShellExecute Lib "shell32.dll" _
            Alias "ShellExecuteA" _
            (ByVal Hwnd As Long, _
            ByVal lpOperation As String, _
            ByVal lpFile As String, _
            ByVal lpParameters As String, _
            ByVal lpDirectory As String, _
            ByVal nShowCmd As Long) As Long
            
Public Const BD_USUARIO = "geslab"
Public Const BD_PASS = "Aer0p0lis2016*"

Public Const PI = 3.14159265358979
Public Const BUZON_CORREO_LOG As String = "julio.gonzalez@ixitec.net"
Public Const USUARIO_VIGILADO As Integer = 33
Public Const USUARIO_VIGILADO_CORREO As String = "informatica@canagrosa.com"
'Public Const USUARIO_VIGILADO_CORREO As String = "informatica@canagrosa.com;julio.gonzalez@ixitec.net"

Public Const RUTA_MUESTRA As String = "ADJUNTOS"
'M0499 Public Const RUTA_OFERTA As String = "OFERTAS-ADJUNTOS"
Public Const RUTA_PEDIDO_CLIENTE As String = "CLIENTES-PEDIDOS-ADJUNTOS"
Public Const RUTA_DECODIFICADORA As String = "DECODIFICADORA"
Public Const RUTA_PROVEEDOR As String = "PROVEEDOR-FACTURAS"

Public Const TIPOS_DOCUMENTOS_INFORMES = "1,2,4,70"
Public Const TIPOS_DOCUMENTOS_METROLOGIA = "100,101"

Public Enum C_ETIQUETAS_TIPOS
    C_ETIQUETAS_TIPOS_REX = 1
    C_ETIQUETAS_TIPOS_MUESTRA = 2
    C_ETIQUETAS_TIPOS_EQ_CAL = 3
    C_ETIQUETAS_TIPOS_EQ_VER = 4
    C_ETIQUETAS_TIPOS_EQ = 5
    C_ETIQUETAS_TIPOS_RPR = 6
End Enum

Public Enum C_TIPO_MAT_REF
    C_TIPO_MAT_REF_OTROS = 5
End Enum
Public Enum C_TIPOS_IMPRESION
    VB_AIRBUS = 4
End Enum
Public Enum TIPOS_DOCUMENTOS
    TIPO_DOCUMENTO_TORQUE_CALIBRACION = 26
    TIPO_DOCUMENTO_TORQUE_VERIFICACION = 27
End Enum
Public Enum CENTROS
    CENTRO_SEVILLA = 1
    CENTRO_GETAFE = 2
    CENTRO_MADRID = 3
End Enum
Public Enum REMESAS
    REMESA_PAGO = 1
    REMESA_COBRO = 2
End Enum
Public Enum ENUM_TIPO_RECARGA
    ENUM_TIPO_RECARGA_OR = 1
    ENUM_TIPO_RECARGA_rR = 2
    ENUM_TIPO_RECARGA_INFORME = 3
End Enum
Public Enum ENUM_PNC_ORIGEN
    ENUM_PNC_ORIGEN_RECLAMACION_CLIENTE = 1
    ENUM_PNC_ORIGEN_AUDITORIA_INTERNA = 2
    ENUM_PNC_ORIGEN_AUDITORIA_EXTERNA = 3
    ENUM_PNC_ORIGEN_DETECCION_INTERNA = 4
    ENUM_PNC_ORIGEN_PROCESOS = 5
    ENUM_PNC_ORIGEN_PROVEEDOR = 6
    ENUM_PNC_ORIGEN_INCIDENCIA_MENOR_CLIENTE = 10
End Enum

Public Enum C_TIPOS_DOCS_PAGO
    C_TIPOS_DOCS_PAGO_ALBARAN = 1
    C_TIPOS_DOCS_PAGO_FACTURA = 2
    C_TIPOS_DOCS_PAGO_ABONO = 3
    C_TIPOS_DOCS_PAGO_PROFORMA = 4
End Enum

Public Enum ADJUNTOS_TIPOS
    ADJUNTOS_TIPOS_MUESTRA = 0
    ADJUNTOS_TIPOS_DECODIFICADORA = 3
    ADJUNTOS_TIPOS_CERTIFICADO = 9
End Enum

Public Enum C_SITUACION
    S_EN_RANGO = 0
    S_LIMITES = 1
    S_FUERA_RANGO = 2
End Enum

Public Enum familia
    alodine = 7
    cliente = 15
    suministros = 13
    productos_controlados = 15
    IBERIA = 36
End Enum

Public Const HC_CREACION As String = "Creación"
Public Const HC_FINALIZACION As String = "Finalización"
Public Const HC_PARADA As String = "Parada/Reanudación"
Public Const HC_ASISTENCIA As String = "Asistencia"
Public Const HC_ADJUNTOS As String = "Adjuntos"
Public Const HC_INVITACIONES As String = "Invitaciones"
'M1110-I
Public Const HC_ASIGNACION As String = "Asignación a PFA"
Public Const HC_DESASIGNACION As String = "Desasignación de PFA"
'M1110-F

Public Enum HC_TIPOS
    HC_BANO = 1
    HC_CE_TIPO_ENSAYO_EFICACIA = 2
    HC_TIPO_ANALISIS = 3
    HC_FLUIDO = 4
    HC_sellante = 5
    HC_CE_FICHA = 6
    HC_CE_FICHA_BANO = 7
    HC_TIPO_DETERMINACION = 8
    HC_Formula = 9
    HC_PINTURA = 10
    HC_OFERTAS = 11
    HC_CLIENTE = 15
    HC_CURSO = 17
    HC_PLASMA_ENSAYOS = 18
    HC_PLASMA_FICHAS = 19
    HC_BANCO = 20
    HC_PLASMA_PROCESOS = 21
    HC_INVENTARIO = 23
    HC_PROCESOS_BASE = 24
    HC_PEDIDOS = 25
    HC_ALODINE_CERTIFICADOS = 26
End Enum

Public Enum MENSAJES_CATEGORIAS
    MENSAJES_CATEGORIAS_NORMAL = 1
    MENSAJES_CATEGORIAS_PROCN = 2
    MENSAJES_CATEGORIAS_OFERTAS = 3
    MENSAJES_CATEGORIAS_EQUIPOS = 4
    MENSAJES_CATEGORIAS_CALIDAD = 5
    MENSAJES_CATEGORIAS_CE = 6
End Enum

Public Enum PINTURAS_ESTADOS
    PINTURAS_PENDIENTE = 1
    PINTURAS_RECEPCIONADO = 2
    PINTURAS_ANULADO = 3
End Enum

Public Enum parametros
    version = 0
    CADENA_CONEXION_PANREAC = 1
    PROVEEDOR_PANREAC = 2
    ETIQUETA_PEQUEÑA = 3
    ETIQUETA_MEDIANA = 4
    ETIQUETA_GRANDE = 5
    LECTOR_FIRMAS = 7
    OUTLOOK = 8
    CUENTA_CONTABLE_CLIENTE = 9
    CUENTA_CONTABLE_IVA = 10
    USUARIOS_ENVIO_CE = 11
    CODIGO_PROVEEDOR_PEDIDO_REACTIVOS = 12
    NUMERO_OFERTA = 13
    REGISTRO_NUEVO_CE = 14
    DIAS_AVISO_CONTROLES_NOINICIADOS = 15
    CUENTA_CONTABLE_IVA0 = 16
    CUENTA_CONTABLE_IVA10 = 17
    CUENTA_CONTABLE_IVA4 = 18
    FECHA_REVISION_PROVEEDORES = 19
    IMPRESORA_ETIQUETAS_PEQUENA = 20
    IMPRESORA_ETIQUETAS_MEDIANA = 21
    IMPRESORA_ETIQUETAS_GRANDE = 22
    ALODINE_CLIENTE_AIRBUS = 23
    MATRAZ_FORMULA = 25
    MATRAZ_CAMPO = 26
    IBERIA_DATOS_DEFECTO_RECEPCION_PLASMA = 27
    CLIENTES_MUESTRAS_PLAZOS = 28
    HENKEL_HOJA_EXCEL = 29
    IVA = 30
    HENKEL_ALTA_MUESTRA = 31
    HENKEL_ALTA_DATOS_DEFECTO = 32
    ADS_DATOS_EXCEL = 33
    AcroPDF = 35
    DETERMINACIONES_PENDIENTES_TEXTO_MATRAZ = 40
    DETERMINACIONES_PENDIENTES_TEXTO_PESAFILTRO = 41
    ENVIO_CORREO_PNT = 45
    CORREO_DISTRIBUCION_CALIDAD = 46
    ENVIO_CORREO_NO_CUALIFICADO = 47
    TIEMPO_INACTIVIDAD = 50
    EC_CORREO = 55
    GESTOR_DOCUMENTOS_RUTA = 60
    RUTA_WWW = 70
    MTQM_CORREO_OR = 71
    PLASMA_FACTURACION_PRECIOS = 80
    PLASMA_FACTURACION_FAMILIA = 81
    USUARIOS_CUADERNO_AVISOS_EQUIPOS = 104
    ACCIONES_CORRECTIVAS_DIAS_PREAVISO = 105
    ESCANER_USO_LOCAL = 106
    ESCANER_USO_LOCAL_RUTA_CARPETA = 107
    REX_USUARIOS_REACTIVOS_TACTIL = 108
    HISTORICO_TOTAL_DIAS_A_CONSOLIDAR = 109
'E0079-I
    RESPONSABLE_TECNICO_EQUIPOS = 100
'E0079-F
'E0137-I
    CODIGOSC_PAQUETES = 101
'E0137-F
'E0181-I
    NUMERO_LOTE = 102
'E0181-F
'E0506-I
    USUARIOS_VEN_EQUIPOS_CVM_EXTERNO = 103
'E0506-F
    MODIFICACION_FECHAS_CALIBRACION_VERIFICACION = 110
    EQ_FECHA_AVISO_MTO_ANNO_SIGUIENTE = 111
    HISTORICO_DIAS_GRAFICAS = 115
    REX_PEDIDO_DESTINATARIO_CORREO = 120
    
    PARAM_USUARIO_VIGILADO = 130
    PARAM_USUARIO_VIGILADO_CORREO = 131
    
    PARAM_USUARIOS_MODIFICAN_VIDA = 132
    PARAM_USUARIOS_MODIFICAN_EQUIPOS_MUESTRA_CERRADA = 133
    PARAM_OFERTAS_COPIA_CORREO = 135
    PARAM_CA_FAMILIAS_NO_VISIBLES = 140
    PARAM_ZOOM_INFORMES = 145
    PARAM_TM_NO_REVISION = 150
    PARAM_TM_NO_FUERA_PLAZO = 151
    
    PARAM_HENKEL_TM = 160
    PARAM_HENKEL_TA = 161
    PARAM_HENKEL_CLIENTE = 162
    PARAM_HENKEL_PROBETAS_DTO = 163
    
    ALODINE_ULTIMO_LOTE_PARAMETROS = 170
    PARAM_TIPOS_BOTE_ALODINE = 200
    BD_DOCUMENTACION_NORMAS = 201
    SPDA_SECUENCIAL = 210
    SPDA_CANTIDAD = 211
    SPDA_TIPO_MUESTRA = 212
    PARAM_TIPO_COMBUSTIBLE = 215
    PARAM_FECHA_AGUAS_AGRUPADAS = 220
    
    FACTURA_DIGITAL_CERTIFICADO = 230
    FACTURA_DIGITAL_RAZON = 231
    FACTURA_DIGITAL_CONTACTO = 232
    FACTURA_DIGITAL_LOCATION = 233
'M1053-I
    PARAM_MUESTRA_IPA = 240
'M1053-F
'TESORERIA-I
    PARAM_CUENTA_CONTABLE_PROVEEDOR = 241
'TESORERIA-F
'M1171-I
    PARAM_CORREO_DISTRIBUCION_TRAMITE = 250
'M1171-F
    PARAM_PLASMA_TM = 260
    PARAM_PLASMA_TA = 261
    PARAM_PLASMA_HORAS = 262
'JGM-I
    PARAM_EQUIPOS_APERTURA_CIERRE = 300
'JGM-F
'M0996-I
    PARAM_TOBJETO = 500
'M0996-F
End Enum

Public Enum OFERTAS_ESTADOS
    OFERTAS_ESTADOS_GENERADA = 0
    OFERTAS_ESTADOS_ENVIADA = 1
    OFERTAS_ESTADOS_ACEPTADA = 2
    OFERTAS_ESTADOS_RECHAZADA = 3
    OFERTAS_ESTADOS_ANULADA = 4
End Enum

Public Enum ENUM_SECTORES
    SECTOR_AGROALIMENTARIO = 8
End Enum


Public Enum DECODIFICADORA
    ESTADOS_OFERTAS = 1
    TIPOS_DE_OFERTAS = 2
    CA_NORMAS_ESTADOS = 3
    CA_NORMAS_TIPOS = 4
    CA_NORMAS_SECTORES = 5
    CA_NORMAS_SUBTIPOS = 6
    CA_DOCUMENTOS_ESTADOS = 7
    CA_DOCUMENTOS_FAMILIAS = 8
    CA_DOCUMENTOS_SUBFAMILIAS = 9
    CA_DOCUMENTOS_RESPONSABLES = 10
    NC_TIPOS_HECHOS = 11
    NC_ORIGENES = 12
    NC_ESTADOS = 13
    NC_DEPARTAMENTOS = 14
    NC_AFECTADO = 15
    NC_DESVIACIONES = 22
    TAREAS_MODULOS = 16
    TAREAS_TIPOS_HORAS = 17
    ERRORES_PRIORIDADES = 20
    ERRORES_TIPOS = 21
    REX_TIPOS = 30
    REX_INVENTARIOS_ESTADOS = 31
    SUBTIPOS_DE_OFERTAS = 32
    SPECIMEN_ID_DENOMINACION = 35
    CALIDAD_PLANTILLAS_DOCUMENTOS = 40
    CALIDAD_PLANTILLAS_NORMAS = 41
    
    IBERIA_ENSAYOS_FISICOS = 45
    IBERIA_REPLACEMENT = 46
    
    EMPLEADOS_DEPARTAMENTOS = 50
    IDIOMAS = 51
    PROVEEDORES_SERVICIOS = 60
    PROVEEDORES_METODOS = 61
    DESCRIPCION_PRODUCTO = 70
    BANOS_CENTROS = 75
    BANOS_AREAS = 76
    BANOS_LINEAS = 77
    
    BANOS_INSTALACIONES = 78
    
    FLUIDOS_PROGRAMAS = 80
    FLUIDOS_CENTROS = 81
    FLUIDOS_TIPOS_ENSAYOS = 82
    FLUIDOS_SECCIONES = 83
    FLUIDOS_ESTACIONES = 84
    PROVEEDORES_RIESGOS_PROBABILIDAD = 85
    DECODIFICADORA_DIMENSIONES = 86
    DECODIFICADORA_MATERIALES = 87
    
    C_CERTIFICATOR_ESTADOS = 95
    EQ_FAMILIAS = 100
    EQ_SITUACIONES = 101
    EQ_periodicidad = 102
    EQ_SINO = 103
    EQ_TIPO_CALIBRACION = 104
    EQ_FAMILIAS_ACCIONES_PLANES_MTO = 105
    EQ_TIPOS_DOCUMENTOS = 131
    EP_EMPRESAS_MENSAJERIA = 106
    
    PROCNC_DEPARTAMENTOS = 107
    PROCNC_GRUPO_ORIGENES = 108
    PROCNC_ORIGENES = 109
    PROCNC_ESTADOS = 110
    PROCNC_ESTADOS_ACCIONES_CORRECTIVAS = 111
    PROCNC_AUDITORIAS = 130
    PROCNC_CLASIFICACION_PROBLEMAS = 115
    C_TIPOS_EQUIPO = 116
    PROCNC_TIPOS_NO_CONFORMIDAD = 119
    PROCNC_ORIGEN = 125
    
    PROCNC_ORIGEN_AUDITORIA_INTERNA = 126
    PROCNC_ORIGEN_AUDITORIA_EXTERNA = 127
    PROCNC_ORIGEN_AUDITORIA_DETECCION = 128
    PROCNC_ACCIONES_TIPOS = 129
    
    EQ_SOLICITUD_OFERTAS = 112
    EQ_PROCEDENCIA_EQUIPOS = 113
    EQ_TIPO_SOLICITUD_OFERTA = 114
    EQ_TIPOS_EQUIPO = 116
    EQ_EVENTOS = 117
    EQ_RAZONES_EVENTOS = 118
    REX_TIPOS_REGISTRO_ALMACEN = 120
    MC_TIPOS_OBSERVACION_ENSAYO = 121
    VIDEOS_TIPO_VIDEO = 122
    EQ_TIPOS_PARAMETROS_RESULTADO = 124
    EQ_UBICACION_ID = 132
    DECO_EXTENSIONES_TELEFONO = 150
'MANTIS-820-I
'M1127-I
'    DECO_EXTENSIONES_USUARIOS = 162
'M1127-F
'MANTIS-820-F
    PEDIDOS_CLIENTES_TIPOS = 151
    ADJUNTOS_TIPOS_DOCUMENTOS = 152
    
    AUDITORIA_MOTIVOS_RETRASOS = 155
    
    PINTURAS_OT = 160
    PINTURAS_ESTADOS = 161
'M1039-I
    INDICADOR_DEPARTAMENTOS = 170
    INDICADOR_APARTADOS = 171
'M1039-F
'M1058-I
    DECODIFICADORA_MONEDA = 180
'M1058-F
'M1058-I
    PP_ESTADOS = 181
'M1058-F
'M1166-I
    REX_USO_PREVISTO_TIPO = 190
    REX_USO_PREVISTO_PERIODICIDAD = 191
    REX_HOMOGENEIDAD = 192
    REX_ESTABILIDAD = 193
    REX_SIST_PRODUCCION = 194
    REX_CERTIFICADO = 195
    REX_INCERTIDUMBRE = 196
    REX_PROCEDIMIENTO = 197
'M1166-F
'M1257-I
    SC_SUBTIPOS = 198
'M1257-F
'M1274-I
    SC_ESTADOS = 199
'M1274-F
'M1110-I
    DECODIFICADORA_MESES = 200
'M1110-F
    DECODIFICADORA_CONTABILIDAD_SUBCUENTAS_GASTOS = 201
    DECODIFICADORA_CONTABILIDAD_SUBCUENTAS_PAGOS = 202
    DECODIFICADORA_CONTABILIDAD_IVA_GASTOS = 203
    
    DECODIFICADORA_PLASMA_RECUBRIMIENTOS = 210
    DECODIFICADORA_PLASMA_TIPOS = 211
    DECODIFICADORA_PLASMA_CLIENTES_INTERNOS = 212
    DECODIFICADORA_PLASMA_FABRICANTES = 213
    DECODIFICADORA_PLASMA_DETERMINACIONES = 214
    
    DECODIFICADORA_GASTOS_TIPOS = 230
    DECODIFICADORA_PERIODICIDADES_FACTURACION = 231
    DECODIFICADORA_PLASMA_PRODUCT_TYPE = 232
    DECODIFICADORA_PLASMA_NUMBER_AND_TYPE = 233
    
    DECODIFICADORA_PROVEEDORES_FP = 250
    DECODIFICADORA_PROVEEDORES_VENCIMIENTOS = 251
    
    DECODIFICADORA_TM_TIPOS_ENSAYOS = 260
    DECODIFICADORA_REMESAS_ESTADOS = 270
    
    DECODIFICADORA_OFERTAS_REQUISITOS = 300
    
    DECODIFICADORA_TOBJETOS = 500
    
    DECODIFICADORA_INVENTARIO_TIPOS = 501
    DECODIFICADORA_INVENTARIO_ZONAS = 502
    
    AIRBUS_PLANT = 600
    AIRBUS_TIPOS_ENSAYOS = 601
    AIRBUS_PROGRAMAS = 602
    AIRBUS_SECTION = 603
    AIRBUS_FLUID = 604
    AIRBUS_FACILITY = 605
    
    DECODIFICADORA_EQUIPOS_CALIBRACIONES_ESTADOS = 902
    DECODIFICADORA_EQUIPOS_CALIBRACIONES_RESULTADOS = 903
    DECODIFICADORA_EQUIPOS_VERIFICACIONES_ESTADOS = 902
    DECODIFICADORA_EQUIPOS_VERIFICACIONES_RESULTADOS = 903
End Enum

Public Const COD_PEDIDO_PROVEEDOR As Long = 99999
Public Const FNULA As String = "1900-01-01"
Public Const GALVATEC As Long = 2291

Public Enum TOBJETO
    TOBJETO_IMAGEN = 0
    TOBJETO_CA_DOCUMENTO = 1
    TOBJETO_CA_NORMA = 2
    TOBJETO_OFERTA = 3
    TOBJETO_NC = 4
    TOBJETO_PROCNC_INCIDENCIA = 5
    TOBJETO_PROCNC_IDENTIFICACION_PROBLEMA = 6
    TOBJETO_PROCNC_RECOLECCION_DATOS = 7
    TOBJETO_EQUIPO = 8
    TOBJETO_PROVEEDOR = 9
    TOBJETO_CLIENTES_PEDIDOS = 10
    TOBJETO_MUESTRAS = 11
    TOBJETO_REX_CERTIFICADOS = 12
    TOBJETO_CLIENTE = 15
    TOBJETO_PAQUETE_SUBCONTRATA = 16
    TOBJETO_CURSO = 17
    TOBJETO_INVITACION_CURSO = 18
    TOBJETO_REX_REACTIVO = 19
    TOBJETO_ASISTENCIA_CURSO_ASISTENTES = 20
    TOBJETO_ASISTENCIA_CURSO_FORMADORES = 21
    TOBJETO_ASISTENCIA_CURSO_CALIDAD = 22
    TOBJETO_LOTE_PROBETA = 23
    TOBJETO_PAQUETE = 24
    TOBJETO_CERTIFICACION = 25
    TOBJETO_CERTIFICACION_CERTIFICADOR = 26
    TOBJETO_CERTIFICACION_RESPONSABLE = 27
    TOBJETO_DOCUMENTO_VALORACION = 29
    TOBJETO_PEDIDO_PROVEEDOR = 30
    TOBJETO_SC_DETERMINACIONES = 31
    TOBJETO_SC_EFICACIA = 32
    TOBJETO_SC_GENERICA = 33
    TOBJETO_REV_EQ_CALIBRACION = 34
    TOBJETO_REV_EQ_VERIFICACION = 35
    TOBJETO_REV_EQ_MANTENIMIENTO = 36
    TOBJETO_PEDIDO_BOTE_EX = 37
    TOBJETO_SC_PEACH = 38
    TOBJETO_PRESTAMOS = 40
    tobjeto_seguro = 41
    TOBJETO_AU_PROGRAMA = 42
    TOBJETO_INVENTARIO = 45
    
    TOBJETO_BANO = 50
    TOBJETO_DECODIFICADORA = 100

End Enum

Public Enum tipo_especial
    BANO = 1
    agua = 2
    control_eficacia = 3
    FLUIDO = 4
    PLASMA = 5
    CONTROLES_PROCESOS = 6
    CAL_EXTERIOR = 7
End Enum
Public Enum TIPOS_MUESTRAS
    TM_AGUA = 2
    TM_BANO = 6
    TRIGO = 10
    HARINA_BLANDA = 34
    SELLANTE = 43
    COMBUSTIBLE = 47
    ESPESOR = 58
    ecs = 74
    TM_FLUIDO = 80
    MICRODUREZA = 90
    TM_ACEITE_MOTOR = 100
    RUGOSIDAD = 102
    CALIBRACION_EXTERIOR = 108
    ENSAYO_TRACCION = 118
    RESISTIVIDAD_TIPO_2 = 147
    DUREZA_ROCKWELL = 160
    DUREZA_VICKERS = 171
    HARINA_DURO = 178
    TM_COMBUSTIBLE_AGRUPADO = 200
    PLASMA = 222
    DUREZA_SHORE_PIEZAS = 225
    DUREZA_BRINELL = 250
    RESISTIVIDAD_TIPO_1 = 308
End Enum

Public Enum C_CA_DOCUMENTOS_ESTADOS
    CA_REVISION = 2
    CA_EN_PROCESO = 3
    CA_POR_HACER = 4
    CA_CADUCADO = 9
    CA_VIGOR = 13
    CA_PDTE_CREACION = 19
    CA_PDTE_MODIFICACION = 20
    CA_PDTE_REVISION = 21
    CA_PDTE_APROBACION = 22
End Enum
Public Enum C_NC_ESTADOS
    ABIERTA = 1
    CERRADA = 2
    PDTE_REVISION = 3
End Enum

Public Enum C_REX_INVENTARIOS_ESTADOS
    ABIERTO = 1
    cerrado = 2
End Enum

Public Enum C_REX_TIPO_REGISTRO_ALMACEN
    REX_RECEPCION = 0
    REX_ENTRADA_ALMACEN = 1
    REX_SALIDA_ALMACEN = 2
    REX_ABRIR_BOTE_SALIDA_ALMACEN = 3
    REX_ENTRADA_SALIDA_ALMACEN = 4 ' INCIDENCIA
    REX_SALIDA_ENTRADA_ALMACEN = 5 ' INCIDENCIA
    REX_FINALIZAR_BOTE_BAJA_BOTE = 6
    REX_IMPRESION_ETIQUETA = 7
End Enum

Public Enum C_NORMAS_FLUIDOS
    IDE44 = 1
    NAS1638 = 2
End Enum

Public Enum C_PROCNC_ESTADOS
    ABIERTA = 1
    PTE_VISTO_BUENO = 2
    EN_TRAMITACION = 3
    PTE_CONFIRMACION_CALIDAD = 4
    PTE_PLAN_ACCIONES_CORRECTIVAS = 5
    pte_cierre = 6
    CERRADA_PARCIAL_EVAL = 7
    CERRADA = 8
End Enum

Public Enum C_PROCNC_ESTADOS_ACCIONES
    ABIERTA = 1
    EN_TRAMITACION = 3
    CERRADA_GENERA_NUEVA_ACCION = 7
    CERRADA_EXITO = 8
End Enum

Public Enum C_PROCNC_NIVELES_ACCESO
    SIN_ACCESO = 0
    SOLO_LECTURA = 1
    SOLO_CORRECTIVAS_ASIGNADAS = 2
    JEFE_EQUIPO_INVESTIGACION = 3
    JEFE_EQUIPO_INVESTIGACION_RESPONSABLE_DEPARTAMENTO = 4
    RESPONSABLE_DEPARTAMENTO = 5
    ACCESO_TOTAL = 6
End Enum


Public Enum enumTipoEdicion
    Alta = 0
    EDICION = 1
    visualizar = 3
End Enum

Public Enum enumTipoAccionTrazabilidad
    WF_ALTA_REGISTRO = 1
    WF_MODIFICACION_REGISTRO = 2
    WF_CAMBIO_ESTADO_REGISTRO = 3
    WF_ENVIAR_REGISTRO_HISTORICO = 4
    WF_CONSULTAR_REGISTRO = 5
    WF_CAMBIO_TIPO = 6
End Enum



Public Enum enumTipoPreguntaRespuesta
    RESP_ALFANUMERICO = 0
    RESP_NUMERICA = 1
    RESP_SINO = 2
End Enum

Public Enum enumIdAux
    ID_AUX_NUEVO = -2
    ID_AUX_EXISTE = 0
    ID_AUX_MODIFICADO = 1
    ID_AUX_ELIMINADO = -1
End Enum

Public Enum C_AU_AREAS_TIPOS_USUARIOS
    AU_TIPO_USUARIO_AUDITOR = 1
    AU_TIPO_USUARIO_AUDITADO = 2
    AU_TIPO_USUARIO_DISTRIBUCION = 3
End Enum
' Plantillas word
Public Const docCOMBUSTIBLE As String = "CO"
Public Const docFLUIDO As String = "FH"
Public Const docFLUIDO_MORADO As String = "FH-MORADO"

'Public Const SQL_BT = "START TRANSACTION;"
'Public Const SQL_ROLL = ";ROLLBACK;"
Public Const SQL_BT = ""
Public Const SQL_ROLL = ""

Public Enum enumDPTO
    GERENCIA = 1
    Calidad = 2
    ADMINISTRACION_RRHH = 3
    LABORATORIO_AGROALIMENTARIO = 4
    LABORATORIO_AERONAUTICO = 5
    METROLOGIA = 6
    LOGISTICA = 7
    I_D = 8
    INFORMATICA = 9
    RECEPCION = 10
    TOTAL_DEPARTAMENTOS = 10
End Enum


Public Enum MC_TIPOS_OBSERVACION
    MCTO_CONTROL_EFICACIA = 1
    MCTO_DETERMINACION = 2
    MCTO_BANO = 3
End Enum

Public Enum TIPOS_DATOS
    TIPOS_DATOS_OBSERVACIONES = 1
    TIPOS_DATOS_TEMPERATURA = 2
    TIPOS_DATOS_HORA_TOMA_MUESTRA = 18
    TIPOS_DATOS_NIVEL = 19
End Enum

Public Enum CALIDAD_VIDA_TIPOS
    CALIDAD_VIDA_TIPOS_DOCUMENTO = 1
    CALIDAD_VIDA_TIPOS_NORMA = 2
End Enum
Public Enum CALIDAD_VIDA_SUBTIPOS
    CALIDAD_VIDA_SUBTIPOS_IMPRESION = 1
    CALIDAD_VIDA_SUBTIPOS_MODIFICACION = 2
    CALIDAD_VIDA_SUBTIPOS_NUEVA_EDICION = 3
End Enum

Public Enum TIPOS_TRIGO
    TIPOS_TRIGO_DURO = 0
    TIPOS_TRIGO_BLANDO = 1
End Enum
Public Enum CLASIFICACION_TRIGOS_DUROS
    CLASIFICACION_TRIGOS_DUROS_PROTEINA = 102
    CLASIFICACION_TRIGOS_DUROS_PROTEINA2 = 1814
    CLASIFICACION_TRIGOS_DUROS_PESO_ESPECIFICO = 92
    CLASIFICACION_TRIGOS_DUROS_HUMEDAD = 93
    CLASIFICACION_TRIGOS_DUROS_CENIZAS = 100
    CLASIFICACION_TRIGOS_DUROS_INDICE_CAIDA = 104
    CLASIFICACION_TRIGOS_DUROS_VITROCIDAD = 111
End Enum
Public Enum CLASIFICACION_TRIGOS_BLANDOS
    CLASIFICACION_TRIGOS_BLANDOS_PROTEINA = 102
    CLASIFICACION_TRIGOS_BLANDOS_PROTEINA2 = 1814
    CLASIFICACION_TRIGOS_BLANDOS_INDICE_CAIDA = 104
    CLASIFICACION_TRIGOS_BLANDOS_HUMEDAD = 93
    CLASIFICACION_TRIGOS_BLANDOS_PESO_ESPECIFICO = 92
End Enum

'M0957-I
'Public Enum SC_TIPOS
'    SC_TIPO_DETERMINACION = 0
'    SC_TIPO_ENSAYO_EFICACIA = 1
'    SC_TIPO_GENERICA = 2
'End Enum

Public Enum SC_ESTADOS
    SC_ESTADO_PENDIENTE = 1
    SC_ESTADO_TRAMITADO = 2
    SC_ESTADO_RECIBIDO = 3
    SC_ESTADO_HISTORICO = 4
End Enum
'M1334-I
Public Enum LONG_CUENTA_BANCARIA_CCC
    entidad = 4
    OFICINA = 4
    DC = 2
    cuenta = 10
End Enum
'M1334-F

Public Const SC_PENDIENTE As String = "PENDIENTE"
Public Const SC_TRAMITADO As String = "TRAMITADO"
Public Const SC_RECIBIDO As String = "RECIBIDO"
'M1274-I
Public Const SC_HISTORICO As String = "HISTORICO"
'M1274-F

Public Const SC_COLOR_PENDIENTE As Variant = vbRed
Public Const SC_COLOR_TRAMITADO As Variant = vbBlue
Public Const SC_COLOR_RECIBIDO As Variant = vbBlack
Public Const SC_COLOR_HISTORICO As Variant = vbBlack
'M0957-F
'M1334-I
Public Type CUENTABANCARIA
    entidad As String
    OFICINA As String
    DC As String
    cuenta As String
End Type
'M1334-F
'M1371-I
'Public Const CAMPO_CONFORMIDAD_DUPLICADO As Integer = 5951
'Public Const CONFORMIDAD_DUPLICADO As String = "CONFORME"
'Public Const NO_CONFORMIDAD_DUPLICADO As String = "NO CONFORME"
Public Const CONFORMIDAD_DUPLICADO As Integer = 1
Public Const NO_CONFORMIDAD_DUPLICADO As Integer = 0
'M1371-F
Public Enum PLASMA_TIPOS
    PT_PLASMA = 1
    PT_DUREZA_VICKERS = 2
    PT_DUREZA_ROCKWELL = 3
    PT_CIZALLADURA = 4
    PT_DUREZA_BRINELL = 5
    PT_DUREZA_SHORE_A = 6
End Enum
Public Enum PLASMA_REPLACEMENT
    PR_ENSAYO = 1
End Enum
Public Enum C_CLIENTES
    CLIENTE_IBERIA = 2620
End Enum
