SELECT A.CODIGO, A.SITUACION_ID, A.LABORATORIO_ID,L1.NOMBRE, B.ID_CALIBRACION,B.FECHA_CALIBRACION,B.LABORATORIO_ID,L2.NOMBRE
FROM EQUIPOS A, 
 CALIBRACIONES B,
(SELECT EQUIPO_ID AS C1, MAX(ID_CALIBRACION) AS C2 FROM CALIBRACIONES GROUP BY 1) AS C,
LABORATORIOS L1, LABORATORIOS L2
WHERE A.ID_EQUIPO = B.EQUIPO_ID
AND A.ID_EQUIPO = C.C1 AND B.ID_CALIBRACION = C.C2
AND A.LABORATORIO_ID <> B.LABORATORIO_ID
AND A.LABORATORIO_ID = L1.ID_LABORATORIO
AND B.LABORATORIO_ID = L2.ID_LABORATORIO
-- and A.CODIGO = 'PE6A7921'
;

SELECT A.CODIGO, B.LABORATORIO_ID, B.* 
FROM EQUIPOS A
INNER JOIN CALIBRACIONES B ON A.ID_EQUIPO = B.EQUIPO_ID
WHERE A.CODIGO = 'PE6A7921'

-- SELECT EQUIPO_ID AS A1, MAX(ID_CALIBRACION) AS A2 FROM CALIBRACIONES GROUP BY 1;