SELECT a.ID_GENERAL, CONCAT(b.codigo,'-',a.ID_PARTICULAR) AS CODIGO,a.FECHA_RECEPCION, b.NOMBRE AS tipos_muestra, ana.NOMBRE AS tipos_analisis,c.NOMBRE AS CLIENTE,a.REFERENCIA_CLIENTE,COUNT(DISTINCT d.ID_DETERMINACION) AS CANTIDAD, GROUP_CONCAT(e.NOMBRE) AS DETERMINACIONES
,CONCAT('A-',dp.NUMERO,'-',YEAR(dp.FECHA_FACTURA)) AS ALBARAN, CONCAT('F-',LPAD(dpf.NUMERO,4,'0'),'-',YEAR(dpf.FECHA_FACTURA)) AS FACTURA
FROM muestras a
INNER join tipos_muestra b ON a.TIPO_MUESTRA_ID = b.ID_TIPO_MUESTRA 
INNER JOIN tipos_analisis ana ON a.TIPO_ANALISIS_ID = ana.ID_TIPO_ANALISIS 
INNER JOIN clientes c ON a.CLIENTE_ID = c.ID_CLIENTE 
LEFT JOIN determinaciones d ON a.ID_MUESTRA = d.MUESTRA_ID 
LEFT JOIN tipos_determinacion e ON d.TIPO_DETERMINACION_ID = e.ID_TIPO_DETERMINACION 
LEFT JOIN docs_pago_muestras dpm ON a.ID_MUESTRA = dpm.MUESTRA_ID 
LEFT JOIN docs_pago dp ON dpm.DOC_ID = dp.ID_DOC 
LEFT JOIN docs_pago dpf ON dpf.id_doc = dp.PAGADO 
WHERE c.IBERIA = 1
AND a.ANNO = 2020
AND a.ANULADA = 0
AND b.CODIGO = 'CO'
GROUP BY a.ID_MUESTRA 