SELECT COUNT(*), SUM(C.PRECIO)
  FROM MUESTRAS A, CLIENTES B, DOCS_PAGO_MUESTRAS C
WHERE A.ANNO = 2012
  AND A.ANULADA = 0
  AND A.CLIENTE_ID = B.ID_CLIENTE
  AND B.AIRBUS = 1
  AND A.ID_MUESTRA = C.MUESTRA_ID 
--  AND A.OP_INSITU = 1
--  AND A.OP_VUELO = 1
AND A.OP_LABMOVIL = 1




