SELECT B.NOMBRE,C.DESCRIPCION,C.PRECIO 
  FROM DOCS_PAGO A, CLIENTES B, DOCS_PAGO_CONCEPTOS C
WHERE A.FECHA_FACTURA >= '2012-01-01' AND A.FECHA_FACTURA <= '2012-12-31'
  AND A.ANULADO = 0
  AND A.CLIENTE_ID = B.ID_CLIENTE
  AND B.AIRBUS = 1
  AND A.ID_DOC = C.DOC_ID 
  order by 1,2



