SELECT DISTINCT A.NOMBRE,D.NOMBRE,D.PNT,D.PROC_REF_EADS, D.NORMATIVA_APLICABLE,C.MINIMO,C.MAXIMO 
FROM tipos_muestra A, TIPOS_ANALISIS B, determinaciones_analisis C, tipos_determinacion D
WHERE A.ID_TIPO_MUESTRA IN (80,47,100)
AND A.ID_TIPO_MUESTRA = B.TIPO_MUESTRA_ID 
AND C.TIPO_ANALISIS_ID = B.ID_TIPO_ANALISIS 
AND C.BANO_ID = 0
and C.TIPO_DETERMINACION_ID = D.ID_TIPO_DETERMINACION 
ORDER BY 1,2