ALTER TABLE `banos`  ADD COLUMN `FACTURA_DETERMINACIONES` INT(1) NOT NULL DEFAULT '0' AFTER `TARIFA_CODIGO_ID`;

UPDATE BANOS B1,  (SELECT B.ID_BANO
				         FROM BANOS B, TIPOS_ANALISIS TA
                    WHERE B.SOLUCION_ID = TA.ID_TIPO_ANALISIS 
                      AND TA.FACTURA_DETERMINACIONES = 1 ) AS B2
   SET FACTURA_DETERMINACIONES = 1
 WHERE B1.ID_BANO = B2.ID_BANO;
 