SELECT M.ID_GENERAL,M.FECHA_RECEPCION,CR.*
fROM MUESTRAS M, TIPOS_ANALISIS TA, CE_RESULTADOS CR
WHERE CLIENTE_ID = 2711 AND FECHA_RECEPCION >= DATE_SUB(CURRENT_DATE(),INTERVAL 3 MONTH)
  AND ANALISIS_MODIFICADO = 2
  AND M.TIPO_ANALISIS_ID = TA.ID_TIPO_ANALISIS
  AND (TA.NOMBRE LIKE '%ADHERENCIA%' OR TA.NOMBRE LIKE '%ESPESOR%')
  AND M.ID_MUESTRA = CR.MUESTRA_ID 
  AND CR.CONFORME = 0
  AND M.CERRADA = 1
ORDER BY ID_MUESTRA DESC