SELECT DISTINCT A.EQUIPO_ID,E.NOMBRE, D.ID_DOCUMENTO,D.CODIGO,D.NOMBRE 
  FROM DETERMINACIONES_EQUIPOS A, DETERMINACIONES B, tipos_determinacion C, CA_DOCUMENTOS D, EQUIPOS E
WHERE A.DETERMINACION_ID = B.ID_DETERMINACION 
  AND B.TIPO_DETERMINACION_ID = C.ID_TIPO_DETERMINACION 
  AND C.PNT_VINCULADO = D.ID_DOCUMENTO 
  AND A.EQUIPO_ID = E.ID_EQUIPO 
  AND C.PNT_VINCULADO <> 0
  ORDER BY 1