SELECT C.ID_BOTE_EX, E.NOMBRE, C.FECHA_CADUCIDAD, C.LOTE
FROM REX_INVENTARIOS A, REX_INVENTARIOS_BOTES B, BOTES_EX C, TIPOS_BOTE_EX D, TIPOS_REACTIVO_EX E
WHERE A.ID_INVENTARIO = B.INVENTARIO_ID 
AND B.BOTE_EX_ID = C.ID_BOTE_EX
AND A.ID_INVENTARIO = 5
AND C.TIPO_BOTE_EX_ID = D.ID_TIPO_BOTE_EX
AND D.TIPO_REACTIVO_EX_ID = E.ID_TIPO_REACTIVO_EX
ORDER BY B.ORDEN  
