SELECT D.NOMBRE,F.NOMBRE, SUM(B.PRECIO)
 FROM DOCS_PAGO A, DOCS_PAGO_MUESTRAS B, MUESTRAS C, CLIENTES D, FAMILIAS F, TIPOS_MUESTRA TM
WHERE A.FECHA_FACTURA >= '2013-01-01' AND A.FECHA_FACTURA <= '2013-12-31'
  AND A.ANULADO = 0 AND A.TIPO = 2
  AND A.ID_DOC = B.DOC_ID 
  AND B.MUESTRA_ID = C.ID_MUESTRA 
  AND B.MUESTRA_ID <> 0
  AND A.CLIENTE_ID = D.ID_CLIENTE 
  AND D.AIRBUS = 1
  AND C.TIPO_MUESTRA_ID = TM.ID_TIPO_MUESTRA
  AND TM.FAMILIA_ID = F.ID_FAMILIA
GROUP BY D.NOMBRE,F.NOMBRE
union

select d.nombre,c.NOMBRE, sum(b.PRECIO)
from docs_pago a, docs_pago_conceptos b, familias c, clientes d
where a.ID_DOC = b.DOC_ID 
  and b.FAMILIA_ID  = c.ID_FAMILIA 
  and a.ANULADO = 0 and a.TIPO = 2 
  and a.FECHA_FACTURA >= '2013-01-01' and a.FECHA_FACTURA <= '2013-12-31'
  and a.CLIENTE_ID = d.ID_CLIENTE 
  and d.AIRBUS = 1
group by d.nombre,c.NOMBRE
  

  
  