SELECT A.NOMBRE, B.ID_PEDIDO, D.DESCRIPCION, B.CODIGO, B.DESCRIPCION, B.IMPORTE, B.FECHA_PEDIDO, C.NUMERO, C.FECHA_FACTURA, C.TOTAL, C.TOTAL - ((C.TOTAL * DESCUENTO) / 100)
FROM CLIENTES A, CLIENTES_PEDIDOS B, DOCS_PAGO C, DECODIFICADORA D
WHERE A.ID_CLIENTE = B.CLIENTE_ID
  AND A.AIRBUS = 1
  AND B.ID_PEDIDO = C.PEDIDO_ID
  AND C.TIPO = 2 
  AND A.ID_CLIENTE = C.CLIENTE_ID
  AND B.TIPO_ID = D.VALOR AND D.CODIGO = 151
ORDER BY A.NOMBRE, B.ID_PEDIDO, C.ID_DOC