SELECT a.ANNO,cen.NOMBRE AS CENTRO, te.NOMBRE AS TIPO_ENSAYO,s.NOMBRE AS SECTOR,c.NOMBRE AS FAMILIA,d.NOMBRE AS TIPO_MUESTRA, b.NOMBRE AS CLIENTE
	   ,if (a.OP_INSITU=0,'S','N') AS IN_SITU
      ,COUNT(*) AS CANTIDAD,sum(a.PRECIO) AS IMPORTE
from muestras a
INNER join clientes b ON a.CLIENTE_ID = b.ID_CLIENTE 
INNER join tipos_muestra d ON a.TIPO_MUESTRA_ID = d.ID_TIPO_MUESTRA
INNER JOIN centros cen ON a.CENTRO_ID = cen.ID_CENTRO 
LEFT JOIN tipos_especial te ON d.TIPO_ESPECIAL_ID = te.ID_TIPO_ESPECIAL 
LEFT join familias c ON c.ID_FAMILIA = d.FAMILIA_ID 
LEFT JOIN sectores s ON s.ID_SECTOR = d.SECTOR_ID 
WHERE a.ANULADA = 0 AND a.ANNO <> 0
group by 1,2,3,4,5,6,7,8