SELECT CASE A.TIPO WHEN 2 THEN 'FACTURA' ELSE 'ABONO' END, A.NUMERO,A.FECHA_FACTURA,B.ID_CLIENTE, 
       B.NOMBRE, A.TOTAL, C.ID_PEDIDO, C.CODIGO,C.DESCRIPCION,C.IMPORTE, CASE A.PAGADO WHEN 0 THEN 'PENDIENTE' ELSE 'COBRADA' END
FROM DOCS_PAGO A, CLIENTES B, CLIENTES_PEDIDOS C
WHERE A.CLIENTE_ID = B.ID_CLIENTE
AND A.PEDIDO_ID = C.ID_PEDIDO 
AND B.NOMBRE LIKE '%AIRBUS%'
AND B.ANULADO = 0
AND A.FECHA_FACTURA >= '2011-01-01'
AND A.TIPO IN (2,3)
AND A.ANULADO = 0
ORDER BY A.FECHA_FACTURA 




