SELECT C.CLIENTE_ID, C.ID_PEDIDO,C.CODIGO,C.DESCRIPCION,B.NOMBRE,C.FECHA_PEDIDO,C.FECHA_BAJA, C.IMPORTE, SUM(A.TOTAL)
FROM DOCS_PAGO A, CLIENTES B, CLIENTES_PEDIDOS C
WHERE A.CLIENTE_ID = B.ID_CLIENTE
AND A.PEDIDO_ID = C.ID_PEDIDO 
AND B.NOMBRE LIKE '%AIRBUS%'
AND B.ANULADO = 0
AND A.FECHA_FACTURA >= '2011-01-01'
AND A.TIPO IN (2,3)
AND A.ANULADO = 0
GROUP BY C.CLIENTE_ID,C.ID_PEDIDO,C.CODIGO,C.DESCRIPCION,C.IMPORTE,B.NOMBRE,C.FECHA_PEDIDO,C.FECHA_BAJA





