SELECT S.NOMBRE,F.NOMBRE,TM.NOMBRE, S.ID_SECTOR,F.ID_FAMILIA,TM.ID_TIPO_MUESTRA 
  FROM TIPOS_MUESTRA TM
 INNER JOIN SECTORES S ON TM.SECTOR_ID = S.ID_SECTOR 
 INNER JOIN FAMILIAS F ON TM.FAMILIA_ID = F.ID_FAMILIA 
WHERE TM.ANULADO = 0

