SELECT M.FECHA_RECEPCION,M.ID_GENERAL, TA.NOMBRE, M.REFERENCIA_CLIENTE, DPM.PRECIO, DP.NUMERO, DP.FECHA_FACTURA
FROM 
MUESTRAS M, DOCS_PAGO DP, DOCS_PAGO_MUESTRAS DPM, TIPOS_ANALISIS TA
WHERE M.ID_MUESTRA = DPM.MUESTRA_ID
AND DPM.DOC_ID = DP.ID_DOC
AND M.TIPO_ANALISIS_ID = TA.ID_TIPO_ANALISIS
AND M.TIPO_MUESTRA_ID = 24
AND M.ANNO >= 2011 AND M.ANULADA = 0
AND DP.TIPO = 2
-- AND DP.CLIENTE_ID = 2599
 AND M.CLIENTE_ID = 2599
