 SELECT AA.C1 AS SECTOR, AA.C2 AS FAMILIA, SUM(AA.C3) FROM
-- SELECT AA.C4, AA.C1 AS SECTOR, AA.C2 AS FAMILIA, SUM(AA.C3) FROM
(
	SELECT DP.NUMERO AS C4, S.NOMBRE AS C1, F.NOMBRE AS C2, SUM(DPM.PRECIO) - ((sum(DPM.PRECIO) * DP.descuento) / 100) AS C3
	FROM MUESTRAS M, TIPOS_MUESTRA TM, SECTORES S, DOCS_PAGO_MUESTRAS DPM, DOCS_PAGO DP, FAMILIAS F
	WHERE M.TIPO_MUESTRA_ID = TM.ID_TIPO_MUESTRA
   and DP.FECHA_FACTURA >= '2013-01-01' and DP.FECHA_FACTURA <= '2013-12-31'
	AND TM.SECTOR_ID = S.ID_SECTOR
	AND TM.FAMILIA_ID = F.ID_FAMILIA
	AND DPM.MUESTRA_ID = M.ID_MUESTRA
	AND DP.ID_DOC = DPM.DOC_ID
	AND DP.TIPO IN (2,3)
	AND DPM.MUESTRA_ID <> 0 
--   and S.id_sector = 0
--	AND F.ID_FAMILIA in (1,16)
	GROUP BY  DP.NUMERO,S.NOMBRE, F.NOMBRE
	UNION
	select a.NUMERO AS C4, s.nombre AS C1,c.NOMBRE AS C2, sum(b.PRECIO) - ((sum(b.PRECIO) * a.descuento) / 100) AS C3
	from docs_pago a, docs_pago_conceptos b, familias c, SECTORES s
	where a.ID_DOC = b.DOC_ID 
	  and b.FAMILIA_ID  = c.ID_FAMILIA 
	  AND c.SECTOR_ID = s.ID_SECTOR
	  and a.ANULADO = 0 and a.TIPO IN (2,3)
	  and a.FECHA_FACTURA >= '2013-01-01' and a.FECHA_FACTURA <= '2013-12-31'
--     and S.id_sector = 0
--	  AND C.ID_FAMILIA = 13
--	AND C.ID_FAMILIA in (1,16)
	group by a.NUMERO, s.nombre,c.NOMBRE
) AS AA  
-- GROUP BY AA.C4, AA.C1, AA.C2
 GROUP BY AA.C1, AA.C2
