 SELECT AA.C4 AS ANNO, AA.C5 AS CLIENTE, AA.C1 AS SECTOR, AA.C2 AS FAMILIA, SUM(AA.C3) FROM
(
	SELECT CLI.NOMBRE AS C5, YEAR(DP.FECHA_FACTURA) AS C4, S.NOMBRE AS C1, F.NOMBRE AS C2, SUM(DPM.PRECIO) - ((sum(DPM.PRECIO) * DP.descuento) / 100) AS C3
	FROM MUESTRAS M, TIPOS_MUESTRA TM, SECTORES S, DOCS_PAGO_MUESTRAS DPM, DOCS_PAGO DP, FAMILIAS F, CLIENTES CLI
	WHERE M.TIPO_MUESTRA_ID = TM.ID_TIPO_MUESTRA
    and DP.FECHA_FACTURA >= '2006-01-01' and DP.FECHA_FACTURA <= '2014-12-31'
	 AND TM.SECTOR_ID = S.ID_SECTOR
	 AND TM.FAMILIA_ID = F.ID_FAMILIA
	 AND DPM.MUESTRA_ID = M.ID_MUESTRA
	 AND DP.ID_DOC = DPM.DOC_ID
	 AND DP.TIPO IN (2,3)
	 AND DPM.MUESTRA_ID <> 0 
	 AND DP.CLIENTE_ID = CLI.ID_CLIENTE
	GROUP BY CLI.NOMBRE,YEAR(DP.FECHA_FACTURA),S.NOMBRE, F.NOMBRE
	UNION
	select CLI.NOMBRE AS C5,YEAR(a.FECHA_FACTURA) AS C4, s.nombre AS C1,c.NOMBRE AS C2, sum(b.PRECIO) - ((sum(b.PRECIO) * a.descuento) / 100) AS C3
	from docs_pago a, docs_pago_conceptos b, familias c, SECTORES s, CLIENTES CLI
	where a.ID_DOC = b.DOC_ID 
	  and b.FAMILIA_ID  = c.ID_FAMILIA 
	  AND c.SECTOR_ID = s.ID_SECTOR
	  and a.ANULADO = 0 and a.TIPO IN (2,3)
	  and a.FECHA_FACTURA >= '2016-01-01' and a.FECHA_FACTURA <= '2014-12-31'
	  AND a.CLIENTE_ID = CLI.ID_CLIENTE
	group by CLI.NOMBRE,YEAR(a.FECHA_FACTURA), s.nombre,c.NOMBRE
) AS AA  
 GROUP BY AA.C4, AA.C5,AA.C1, AA.C2
